apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-k8s-example.fullname" . }}
  labels:
    {{- include "helm-k8s-example.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # nodePort:  {{ .Values.service.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-k8s-example.selectorLabels" . | nindent 4 }}
