Vagrant.configure("2") do |config|
  config.vm.define "k8s-master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "k8s-master"
    master.vm.network 'private_network', ip: "192.168.50.10"
    master.vm.provider :virtualbox do |vb|
      vb.name = "k8s-master"
      vb.memory = "2048"
      vb.cpus = 2
    end
  end

  config.vm.define "k8s-slave" do |slave|
    slave.vm.box = "ubuntu/bionic64"
    slave.vm.hostname = "k8s-slave"
    slave.vm.network 'private_network', ip: "192.168.50.11"
    slave.vm.provider :virtualbox do |vb|
      vb.name = "k8s-slave"
    end
  end
end
